### PR TITLE
convert to immediately invoked function expression

### PR DESCRIPTION
**Pull request by icopp**
Using an IIFE (https://developer.mozilla.org/en-US/docs/Glossary/IIFE) prevents unintended conflicts with global-scope variables and functions (like other scripts on a page, Google ads or analytics, etc). It's not super important here, since the page only does one thing, but it's good practice for the future.

To see what the actual diff is, turn on `Files changes -> Diff settings -> Hide whitespace changes`.

### CODE REVIEW

**Comment by S-poony** [comment]
Thank you so much ! Badly I modified the code a bit (just the size of the score) before seeing your pull request :/ could you please update it so I can merge it ?

**Comment by icopp** [comment]
Done!

**Comment by S-poony** [comment]
You are so nice !

**Comment by S-poony** [comment]
You are so nice !

**Pull request merged**
