### PR TITLE
convert to let and const statements and capitalized constants

### PR DESCRIPTION
**Pull request by icopp**
This does two things:

- convert from `var` and some unlabeled vars to using `let` and `const` for everything
  - `let` is like `var`, but it makes it easier to avoid some weird obscure bugs you can get from `var` in some situations. [You can see the technical stuff here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), but [sites like StackOverflow have practical examples](https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable-in-jav).
  - `const` means it can't be reassigned. You can do `let a = 5; a = 6;`, but you can't do `const a = 5; a = 6` (it will error). This allows for better performance, because the browser can keep just the static value.
- changes the names of simple constants to be `ALL_IN_UPPERCASE_LIKE_THIS`
  - There's no special reason for this. It's just very common among JS developers.

### CODE REVIEW

**Comment by S-poony** [comment]
Thank you for explaining me all of this !

**Comment by lovasoa** [comment]
I am not sure adding let and const is a great idea... This breaks compatibility with older browsers and doesn't bring any practical gain...

**Comment by icopp** [comment]
It is true that let and const don't work in old browsers, but [they're supported in every current browser version](https://caniuse.com/#feat=const), and for a starting project like this it's much better to get into good future habits than to immediately worry about supporting IE 10.

**Comment by lovasoa** [comment]
Let me disagree. There is a lot to learn before getting into small details like that. 

@S-poony : I would advise you to switch back to var. This will make the game work again for your users for whom the game stopped working after you merged this PR. We will later get into the details of compiled JavaScript that will allow you to use let and const without sacrifycing old browser compatibility, but there is a lot of JavaScript features we still have to discover together that are much more exciting and are available in all browsers, such as arrays and loops.

**Comment by lovasoa** [comment]
The best habit is the habit of not breaking things that work.

**Comment by lovasoa** [comment]
The best habit is the habit of not breaking things that work.

**Comment by S-poony** [comment]
I'm taking my pop corns

**Pull request merged**
